### ISSUE TITLE
Object of type 'Hashid' is not JSON serializable

### ISSUE THREAD

**Issue by Bartvds** [nshafer/django-hashid-field#11]
The regular JSON encoders can't handle the Hashid object, so we had to override the encoder to use the hashed value instead of the instance:

````python
class HashidJSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, Hashid):
            return str(o)
        return super().default(o)
````

This is not that surprising or new, but I'd leave a note.

**Comment by Bartvds** [comment]
I'll close this for now as it was informational for other searchers.

**Comment by csurbier** [comment]
Hi,

I have this problem with Django 1.11 and Django Rest Framework 3.7.3 :
TypeError: Hashid(1): RzvM8ln is not JSON serializable

Can you explain me what should I do and/or where I should override the JSON encoder in DRF?

Thanks a lot

**Comment by dashdanw** [comment]
how come this is closed? is this project discontinued?

**Comment by nshafer** [comment]
I wasn't aware this was really an issue, as I've never had a problem with it, and the sandbox in this project uses DRF just fine without having to override DjangoJSONEncoder. Are you getting the same problem?

**Comment by mjnaderi** [comment]
I had the same issue. I was trying to store `pk` (which is a hashid field) in a JSONField (https://github.com/rpkilby/jsonfield). I solved my issue by passing a customized JSON encoder (as stated by @Bartvds) to JSONField.

**Comment by stfenjobs** [comment]
Make sure that each models.ForeignKey is declared in Serializer:

like this:
```
user = serializers.PrimaryKeyRelatedField(
        pk_field=HashidSerializerCharField(source_field='appname.modelname.id'),
        read_only=True)
```

chinese version:
在model里，所有用了models.ForeignKey的字段， 在Serializer文件里，必须 用这种格式：
```
user = serializers.PrimaryKeyRelatedField(
        pk_field=HashidSerializerCharField(source_field='appname.modelname.id'),
        read_only=True)
```

不然就会提示错误， 而且很难排查  ， 我花了一整天都没有找出原因，最后通过删减字段，才搞定

**Comment by stfenjobs** [comment]
![image](https://user-images.githubusercontent.com/6580897/90317710-d5320880-df5d-11ea-9d94-fe9e0c026ac3.png)

**Comment by sdementen** [comment]
I have the issue when the package django-impersonate push the hashid of my customer user class in the session and django tries to sign the session. For this, django convert the content of the session to JSON which triggers the exception.

```python
Traceback (most recent call last):
  File "...\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "...\lib\site-packages\django\utils\deprecation.py", line 116, in __call__
    response = self.process_response(request, response)
  File "...\lib\site-packages\django\contrib\sessions\middleware.py", line 63, in process_response
    request.session.save()
  File "...\lib\site-packages\django\contrib\sessions\backends\db.py", line 83, in save
    obj = self.create_model_instance(data)
  File "...\lib\site-packages\django\contrib\sessions\backends\db.py", line 70, in create_model_instance
    session_data=self.encode(data),
  File "...\lib\site-packages\django\contrib\sessions\backends\base.py", line 114, in encode
    return signing.dumps(
  File "...\lib\site-packages\django\core\signing.py", line 110, in dumps
    data = serializer().dumps(obj)
  File "...\lib\site-packages\django\core\signing.py", line 87, in dumps
    return json.dumps(obj, separators=(',', ':')).encode('latin-1')
  File "...\Lib\json\__init__.py", line 234, in dumps
    return cls(
  File "...\Lib\json\encoder.py", line 206, in encode
    chunks = list(chunks)
  File "...\Lib\json\encoder.py", line 442, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "...\Lib\json\encoder.py", line 413, in _iterencode_dict
    yield from chunks
  File "...\Lib\json\encoder.py", line 449, in _iterencode
    o = _default(o)
  File "...\Lib\json\encoder.py", line 182, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Hashid is not JSON serializable
```
The content of the session `data` (in `session_data=self.encode(data),` in the traceback) that will be JSON serialized is
`{..., '_impersonate': Hashid(2): b3ZRvZr, '_impersonate_start': 1607524600.914942, ...}`.

**Comment by dbinetti** [comment]
I've had the same problem when using Auth0.  I updated my SESSION_SERIALIZER per @Bartvds 

```
from django.contrib.sessions.serializers import JSONSerializer
from hashid_field import Hashid


class HashidJSONEncoder(JSONSerializer):
    def default(self, o):
        if isinstance(o, Hashid):
            return str(o)
        return super().default(o)
```
