### ISSUE TITLE
What's the best way of handling these in forms.

### ISSUE THREAD

**Issue by tolomea** [nshafer/django-hashid-field#15]
I have various places where id's come in through forms, do you have any guidance on how to validate these at the form level so as to avoid TypeErrors when looking them up in the ORM

    TypeError: 'bob' value must be a positive integer or a valid Hashids string.

**Comment by tolomea** [comment]
And related to that what is a good way to create fake id's that pass the validation.

Currently I've gone with this hackery, which works but seems inelegant:
In the top level of models:
    
    id_field = HashidAutoField(primary_key=True, min_length=12, editable=False)

In my common base model

    id = id_field

For form fields (there's other stuff in this clean I'm omitting here, hence why it's in a clean)

    class FKField(forms.CharField):
        def clean(self, value):
            value = super().clean(value)
            try:
                models.id_field.encode_id(value)
            except ValueError:
                raise ValidationError('incorrectly formatted pk')
        return value

And to generate a valid non existent id in a test

    str(id_field.encode_id(123))

**Comment by nshafer** [comment]
As long as validation happens in the form in a normal way, it should translate any TypeError exceptions into ValidationErrors, and show up in the form. At least, this is what I see with my tests and sandbox usage. Perhaps you have a specific use-case that still gets a TypeError through?
