### ISSUE TITLE
Multiple search_fields in Django admin causes TypeError exception

### ISSUE THREAD

**Issue by berezovskyi-oleksandr** [nshafer/django-hashid-field#16]
When I want to search over some CharField and HashidAutoField in Django Admin, I get 
`TypeError: 'search' value must be a positive integer or a valid Hashids string.`

This fields are set via `search_fields` in admin configuration

**Comment by nshafer** [comment]
This is very related to Issue #17, where I have written a (long rambling) discussion of the issue, that I would love your feedback on.

**Comment by nshafer** [comment]
This is fixed in 2.0.1. Please read the CHANGELOG for upgrading instructions.
