### ISSUE TITLE
IntegrityError for ForeignKey in DRF Request POST

### ISSUE THREAD

**Issue by darius-simiyu** [nshafer/django-hashid-field#19]
Hello,
I've just installed this package in my project and after following the guide, I'm getting an Integrity Error when performing POST requests.
I'll use an example to demo:
```
#models.py
class Book(models.Model):
	id = HashidAutoField(primary_key=True)
	title = models.CharField(max_length=200)
	isbn = models.CharField(max_length=50)
	author = models.ForeignKey('Author', related_name='book')

class Author(models.Model):
	id = HashidAutoField(primary_key=True)
	name = models.CharField(max_length=100)
	books = models.ForeignKey(Book, related_name="author")
```

```
#serializers.py
class BookSerializer(serializers.ModelSerializer):
	id = HashidSerializerCharField(source_field='my_app.Book.id')
	author = serializers.PrimaryKeyRelatedField(pk_field=HashidSerializerCharField(source_field='my_app.Author.id'), read_only=True)
    
    class Meta:
        model = Book
        fields = ("id", "title", "isbn", "author")


class AuthorSerializer(serializers.ModelSerializer):
    id = HashidSerializerCharField(source_field='my_app.Author.id')
    
    class Meta:
        model = Author
        fields = ("id", "name")
```

```
#views.py
class BooksList(APIView):
	def get(self, request, format=None):
		a_list = Book.objects.all()
		serializer = BookSerializer(a_list, many=True)
		return Response(serializer.data)

	def post(self, request, format=None):
		serializer = BookSerializer(data=request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

	def delete(self, request, pk, format=None):
		item = self.get_object(pk)
		item.delete()
		return Response(status=status.HTTP_204_NO_CONTENT)

class BookDetail(APIView):
	def get_object(self, pk):
        try:
            return Book.objects.get(pk=pk)
        except Book.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        item_list = self.get_object(pk)
        item_list = BookSerializer(item_list)
        return Response(item_list.data)

    def put(self, request, pk, format=None):
        item = self.get_object(pk)
        serializer = Book(item, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        item = self.get_object(pk)
        item.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
```

```
#urls.py
url_patterns = [
....
    url(r'^api/books/$', views.BooksList.as_view()),
    url(r'^api/books/(?P<pk>\w+)/$', views.BookDetail.as_view()),
....
```

I use token authentication for my APIs,
Now when I do a POST
curl -X POST 'http:localhost:8000/my_app/books/' -H "Authorizations: Token my_token_here" -d "title=TestBook&isbn=1234567890&author=7a5kPOq"

I get an error 
IntegrityError at /my_app/api/books/ NOT NULL constraint failed:my_app_book.author_id Request Method: POST Request URL: http://localhost:8000/my_app/api/books/
(I have an author whose id = 7a5kPOq)

django == 1.11.6
django-hashid-fields == 2.0.1

The same worked before I introduced the HashidAutoField. Why can't it recognize the

**Comment by nshafer** [comment]
Hmm, it looks like there's something tricky going on here, probably with the descriptor on the HashidAutoField, versus what normally happens with a regular AutoField. I will attempt to duplicate and look into it (probably this weekend, super busy with work this week), but in meantime, try setting `author_id` in the POST data instead of `author` and tell me if that makes any difference.

**Comment by darius-simiyu** [comment]
I did, but still not working, I still get the IntegrityError. My guessing is probably the to_representation function is not returning a value.

**Comment by nshafer** [comment]
Just wanted to let you know I haven't forgotten you, I just haven't had time to look into this yet. It's been absolutely crazy lately. I used up what time I had with merging some PRs, but I will attempt to get to this in the next couple weeks. Thankfully you have a workaround for now. =)

**Comment by csurbier** [comment]
Hi, 

I have the same issue than Darius. Any progress on this issue ? 

Thanks a lot.

**Comment by zakone** [comment]
Hi,
I had the same issue and I fixed it by changing the PrimaryKeyRelatedField "read_only=True" to "queryset=YourModel.objects.all()" , Then the POST worked.

f.e: 
author = serializers.PrimaryKeyRelatedField(pk_field=HashidSerializerCharField(source_field='my_app.Author.id'), queryset=Author.objects.all())

Hope this helps~

**Comment by nshafer** [comment]
Yes, @zakone is correct, this actually has nothing to do with django-hashid-fields, as is the behavior of DRF. The [docs on serializer relationships](http://www.django-rest-framework.org/api-guide/relations/#primarykeyrelatedfield) states, "queryset - The queryset used for model instance lookups when validating the field input. Relationships must either set a queryset explicitly, or set read_only=True." I had a note about this in the documentation, but I am changing it slightly to be more explicit. Thanks!
