### ISSUE TITLE
Fixtures error

### ISSUE THREAD

**Issue by Jastrzebowski** [nshafer/django-hashid-field#2]
I'm getting an error while trying to load fixtures after initial migration (migration for existing data works fine)

Error as result of `python manage.py loaddata initial_data`:
```
TypeError: Problem installing fixture '/project/app/fixtures/initial_data.json': Hashid(1): HASH is not JSON serializable
```

model.py:
```
class Object(models.Model):
    id = HashidAutoField(
        primary_key=True,
        min_length=6
    )
```

fixture:
```
[
  {
    "model": "app.object",
    "pk": 1,
    "fields": {
     …
    }
  }
]

**Comment by nshafer** [comment]
Thanks for the report @Jastrzebowski, but I'm having problems duplicating the issue. I've tested with Python 2.7 and 3.5 each with Django 1.8, 1.9 and 1.10, and I can't duplicate the error. In all instances I'm able to `dumpdata` and `loaddata` with keys as either integers or strings. Maybe you could shed some light on your environment? What version of Python and Django are you using? Are there any other fields in your models using HashidField or HashidAutoField? Anything else that might help me narrow down the issue?

**Comment by dashdanw** [comment]
works for me on
Python 3.6.8
```
Django==2.1
djangorestframework==3.10.2
```

using the APIClient from DRF
