### ISSUE TITLE
Clarify readme about searching in the admin

### ISSUE THREAD

**Issue by nwolff** [nshafer/django-hashid-field#23]
The readme says: "Supports common filtering lookups, such as field__icontains so that Django Admin search_fields works out of the box."

In reality only exact matches work in the admin: the code in lookups.py tries to interpret the full string that was entered in the search box as a hashid, if it cannot then the search returns no items (or raises an exception depending on HASHID_FIELD_LOOKUP_EXCEPTION ). 

Given that only an integer id is stored in the database (and not the hashid string), it makes sense that partial searches dont work (that would require generating all hashid values starting at one, and comparing to the search string). What I suggest is clarifying the docs.

**Comment by nshafer** [comment]
Thank you for pointing this out. I think when I wrote the docs I was thinking of the fact that a basic search in the admin runs an `__icontains` query, so I made efforts to make that at least work when pasting in hashids. I will clarify the docs to specify that it works with an `__icontains` and others, but they do full-string matches and are case sensitive per the way that Hashids works.
