### ISSUE TITLE
Lookups fail for autofield when the base id is zero

### ISSUE THREAD

**Issue by fpghost** [nshafer/django-hashid-field#29]
In hashid_field/hashid.py I think it should read like:

```
        value = self.decode(id)
        # NB value could be zero
        if value is not None:
            self._id = value
            self._hashid = id
```

else if `value=0` like it would be for an AutoField starting from zero, then decode appears to fail and it leads to valueerror even though the decode actually returned a non-null value

**Comment by nshafer** [comment]
Thanks! I added a test and merged your PR. Fixed in version 2.1.5.
