### ISSUE TITLE
Usage with generic views

### ISSUE THREAD

**Issue by guillaumervls** [nshafer/django-hashid-field#3]
Hi,

Thanks for the package! When I use `id = HashidAutoField(primary_key=True)` on a model, it works fine, except that if I use a Django generic `DetailView` with this model, accessible from a url `url(r'^models/(?P<pk>[0-9a-zA-Z]+)/$', views.MyView.as_view())` it works with both hashes and *real IDs*. Which is a problem if I understand well the purpose of hashids - prevent sequential scraping.

Am I missing something ?

Cheers

**Comment by nshafer** [comment]
Hey, sorry I missed this Issue, for some reason GitHub never emailed me about it, so I didn't see it until just now.

For my use-case where I'm using Hashids, I just use it to make the URLs pretty, and I don't rely on it for security. I definitely think that's the best way to use Hashids, as [it can be cracked pretty easily.](http://hashids.org/#decoding).

That said, I can see it being useful to not allow sequential scraping. I think changing the behavior of the field would be highly problematic specifically when it came to using the field as a target of ForeignKey and ManyToMany fields, so I'll have to think about this and play around with some ideas and get back to you.

**Comment by nshafer** [comment]
I just pushed a [new version](https://pypi.python.org/pypi/django-hashid-field/1.2.0) that adds a `allow_int` or global `HASHID_FIELD_ALLOW_INT` setting to turn off that behavor. By default it will work the same as before, so make sure you set allow_int to False to give it a try after upgrading. Please let me know how it works out.
