### ISSUE TITLE
Should not limit maximum version of Django

### ISSUE THREAD

**Issue by eseglem** [nshafer/django-hashid-field#32]
This line here users from upgrading to Django 2.2:

https://github.com/nshafer/django-hashid-field/blob/master/setup.py#L117 

This seems to be the only library I can find that limits the maximum version like this. Was there a specific reason as to not support more recent versions of Django?

**Comment by nshafer** [comment]
You're right that I shouldn't limit it. I believe I was just thinking about supported versions that I test against. I will remove the upper constraint as I push a new version here shortly.

**Comment by nshafer** [comment]
Version 2.1.6 is now available on pypi that supports Django 2.2 and without the upper django version requirement. Thank you for your patience.

**Comment by eseglem** [comment]
Thank you for the quick turnaround.
