### ISSUE TITLE
Is it possible to set some of the ids manually?

### ISSUE THREAD

**Issue by rootux** [nshafer/django-hashid-field#34]
We would like to do something like that - 
```
new = Image()
new.id = 1000
new.save()
```
Did someone was able to do so with that library?

**Comment by nshafer** [comment]
Yes you can do that, see the [basic usage](https://github.com/nshafer/django-hashid-field#basic-usage). You can do it with HashidAutoFields as well, but those will have a unique index, so you need to make sure the ID that you assign is unique, just like a normal AutoField.
