### ISSUE TITLE
Remove Python 2.7 support

### ISSUE THREAD

**Issue by pauloxnet** [nshafer/django-hashid-field#35]
[Official support for Python 2.7 ends in two months](https://pythonclock.org/), after which no bug fixes or security updates will be released. In preparation for that, I think it is time to remove code from Django Hashid field related to Python 2.7, as well as removing Python 2.7 from the CI test matrix.

The following checklist can tracks the progress of this endeavour:

- [x] remove Python 2 support in `.travis.yml` and `tox.ini`
- [x] remove Python 2 classifiers in `setup.py`
- [x] remove `six` from the code
- [x] remove `__future__` statements from the code
- [x] update `README.rst` accordingly
- [x] convert `super()` calls to python 3 style

**Comment by nshafer** [comment]
This is done in 3.0.0
