### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by hhamana** [nshafer/django-hashid-field#36]
Upon updating to Django 3.0, the following import error is raised on server startup:
```
File "C:\dev\myproject\venv\lib\site-packages\hashid_field\hashid.py", line 4, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (C:\dev\myproject\venv\lib\site-packages\django\utils\__init__.py)
```
It appears `django.utils` indeed does not include a `six` module anymore. Possibly since I am updating an existing project, it was already included in my dependencies as such: `six==1.12.0`.
It was then possible to directly change the import in both `hashid_field.hashid` and `hashid_field.rest`.
```
from django.util import six
```
to simply 
```
import six
```
This fixed it, and I haven't noticed any other error related to django-hashid-field.

Declaring `six` as an independent dependency instead of relying on Django' reexport **may** fix it for everyone with no backwards compatibility issue for users not upgrading their Django yet.

At least that's the easy fix. Considering `six` itself is a Python 2/3 compatibility library, and Django's removal is due to dropping support for Python 2.7, as it reaches end of LTS in January 2020, it might be possible to consider dropping it here too, as suggested in #35.

**Comment by nshafer** [comment]
This is done in 3.0.0. Thanks for your help!
