### ISSUE TITLE
Need to support gt operator to iterate by chunks

### ISSUE THREAD

**Issue by frossigneux** [nshafer/django-hashid-field#38]
I am using django-chunkator to chunk big querysets and save RAM.
It find the next chunk by doing `filter(pk__gt=pk)` (see [here](https://github.com/peopledoc/django-chunkator/blob/master/chunkator/__init__.py#L37)).
However _gt_ operator is not supported by django-hashid-field.
Is there a particular reason to do not support it with integers?
We can get similar result by doing `Model.objets.all()[start:]` but I am not sure of the memory efficiency.
I opened an issue here: https://github.com/peopledoc/django-chunkator/issues/36

**Comment by nshafer** [comment]
I looked into it, and due to other changes I made with the 3.0 release, it was easy to just add support for `gt`, `gte`, `lt` and `lte`. So 3.1.0 is released with that support. I did not test it explicitly with django-chunkator, so could you give it a try and let me know the result? Thanks.

**Comment by frossigneux** [comment]
Thanks. It works perfectly with django-chunkator now!

However, I am wondering if there is not a security issue.
I have int lookup disabled and get this result:

```
Image.objects.filter(id=1)
<QuerySet []>

Image.objects.filter(id__lte=1, id__gte=1)
<QuerySet [<Image: Image object (BOZt4G6)>]>
```

**Comment by nshafer** [comment]
You are correct... unpublishing 3.1.0 until I have a chance to do this properly. Thanks for catching that.

**Comment by nshafer** [comment]
3.1.1 released with this done properly, and tests fixed to catch this potential problem. Thanks for letting me know!
