### ISSUE TITLE
Not clear on how to serialize a ForeignKey to a model using HashidAutoField

### ISSUE THREAD

**Issue by pembo13** [nshafer/django-hashid-field#4]
I was getting serialization errors as the serialize didn't know how to serialize the foreign models PK.

As a temporary workaround, I did this, but I suspect it's not the best way:

```python
class HashidSerializerRelatedField(serializers.RelatedField):

	def to_representation(self, value):
		return str(value.id)
	
	pass
```

**Comment by nshafer** [comment]
Thanks for bringing this up, I hadn't given it any thought and hadn't run across it myself. After reading through DRF's docs and playing around with an example situation in my sandbox, I think the best solution is to continue to use DRF's PrimaryKeyRelatedField, and just tell it to use the HashidSerializer*Field you want to use by setting its `pk_field` attribute. I just [updated the docs](https://github.com/nshafer/django-hashid-field#primary-key-related-fields) with more information that will hopefully explain it. You can also see some examples in [sandbox/library/serializers.py](https://github.com/nshafer/django-hashid-field/blob/master/sandbox/library/serializers.py). Hope that helps!

**Comment by nshafer** [comment]
BTW, I'll keep this issue open for now. Let me know if that works for you or not in your situation.

**Comment by pembo13** [comment]
That works perfectly, and thanks for updating the docs.
