### ISSUE TITLE
Salt based on foreign_key

### ISSUE THREAD

**Issue by epschroeder** [nshafer/django-hashid-field#47]
Hi everyone,

I would like to implement hashid's in my project but wonder if it's possible to use a foreign_key in a model as salt for the hashid? If this is not possible, is there any other way of using a different salt for each model?

Regards,
Egbert

**Comment by nshafer** [comment]
I'm not sure exactly what you're trying to accomplish, but no there is no way to set the salt based on another field, including a ForeignKey. You *can* set the salt different for every field or every model if you like though, as [detailed under Field Parameters](https://github.com/nshafer/django-hashid-field#field-parameters) in the docs.
