### ISSUE TITLE
Error in HashidAutoField example in readme?

### ISSUE THREAD

**Issue by Bartvds** [nshafer/django-hashid-field#5]
If I follow this example from the readme:

````
from hashid_field import HashidAutoField

class Book(models.Model):
    serial_id = HashidAutoField()
````

I get an error "A model can't have more than one AutoField." (likely because django created an 'id' autofield itself). This is on Django 1.11 and django-hashid-field 1.2.1

It need primary_key=True at least.

**Comment by nshafer** [comment]
Whoops, didn't even notice that when I wrote the docs, and apparently didn't even test that particular use-case. Was more interested in making the point I guess. Thanks for pointing that out!
