### ISSUE TITLE
Migrations and existing data

### ISSUE THREAD

**Issue by sjdweb** [nshafer/django-hashid-field#52]
I'm wondering what the best way to handle existing db rows, and how to get the new HashidField() initialized during a migration? Setting the default value to None fails.

I saw `migrations.RunPython()` in the Django docs, and wondered if I could somehow pull the data and modify it in flight, but seems the column will still need a default value. Happy to update the docs if there is a standard way here.

**Comment by sjdweb** [comment]
Here's a first pass:


```python
from django.db import migrations
import hashid_field.field
from hashid_field import Hashid


def generate_hashids(apps, schema_editor):
    Thing = apps.get_model("myapp", "Thing")
    for t in Thing.objects.all():
        t.reference_id = Hashid(t.id)
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("thing", "0004_created_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="reference_id",
            field=hashid_field.field.HashidField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                default=None,
                min_length=7,
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(generate_hashids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="thing",
            name="reference_id",
            field=hashid_field.field.HashidField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                min_length=7,
                null=False,
            ),
            preserve_default=False,
        ),
    ]

```

**Comment by nshafer** [comment]
This is not unique to HashidsFields, it's a problem when adding any new field to an existing model, and your method for addressing it is in fact correct. Add the field with `null=True`, populate it with a data migration, then alter it to be `null=False`. Depending on the database, you may need to split this into two migrations in my experience. Postgres doesn't seem to like populating a field in the same transaction as it's added. Or I'm thinking of a different case I've hit before.

However, your specific example is not the way this library was designed to be used. It looks like you added a new field called `reference_id` that is the Hashids version of the integer in `id`. This module was designed to be dropped in place of the existing `id` field, and wouldn't require this migration at all. The underlying integers aren't touched, just the representation of them in the Django app. Please see [https://github.com/nshafer/django-hashid-field#hashid-auto-field] the section on AutoHashidField in the README.
