### ISSUE TITLE
Filtering by hash id lookup

### ISSUE THREAD

**Issue by jcobacho** [nshafer/django-hashid-field#59]
can anyone explain this to me:

"Supports common filtering lookups, such as __iexact, __contains, __icontains, though matching is the same as __exact."

```
hash = 'La8yq8O'
filter(hash__icontains='La' -> False
filter(hash__icontains='La8yq8O' -> True
```
is this the part "though matching is the same as __exact" if so then it does not support the other filter
is there a way around this?

**Comment by nshafer** [comment]
This is an artifact of the id being an integer in the database, not a varchar. So it can't convert a partial hashid to an integer to do the lookup, nor can it just do a `hash like 'La%'` query. These other filter lookups are implemented mainly to work with the default django admin.
