### ISSUE TITLE
Reduced alphabet size when initializing a Hashid object and the `hashids` argument is not None

### ISSUE THREAD

**Issue by sgex** [nshafer/django-hashid-field#60]
This commit https://github.com/nshafer/django-hashid-field/commit/a8e83664570d46da79ddd01be6fb00204080791c seems to be incorrectly copying the alphabet at line 19 (`self._alphabet = hashids._alphabet`).

In `Hashids` the alphabet does [not include separators](https://github.com/davidaurelio/hashids-python/blob/09f879a1967836f1e399c12b745c24291e3e73ad/hashids.py#L181) so the [`alphabet`](https://github.com/davidaurelio/hashids-python/blob/09f879a1967836f1e399c12b745c24291e3e73ad/hashids.py#L169) argument passed into the constructor of `Hashids` is different from [`self._alphabet`](https://github.com/davidaurelio/hashids-python/blob/09f879a1967836f1e399c12b745c24291e3e73ad/hashids.py#L208).

A common input alphabet is `0123456789abcdef`. After separators are removed, `hashids._alphabet` will have fewer than the minimum of 16 characters, which is possibly the cause for https://github.com/nshafer/django-hashid-field/issues/44

The old code didn't have this problem because it was not reading `hashids._alphabet`

**Comment by nshafer** [comment]
Thanks for the detailed report. I still can't reproduce #44, but this definitely caused issues with pickling and unpickling. I have fixed it in 3.3.0.
