### ISSUE TITLE
values_list return string insted of HASHID object

### ISSUE THREAD

**Issue by Arti3DPlayer** [nshafer/django-hashid-field#61]
`Model.objects.values_list("id", flat=True)`

returns list of HashID objects that require additional conversion to string. Is this possible to return flat string instead ?

**Comment by nshafer** [comment]
For future reference (anyone that finds this issue), the Hashid object can be turned off by either setting  `HASHID_FIELD_ENABLE_HASHID_OBJECT = False` in the Django settings, or passing `enable_hashid_object=False` in the Hashid*Field constructor. See README for more info.
