### ISSUE TITLE
`enable_hashid_object=False` breaks Django admin?

### ISSUE THREAD

**Issue by ckcollab** [nshafer/django-hashid-field#69]
```py
order_id = HashidField(enable_hashid_object=False, null=True, blank=True)
```

Unless I set `enable_hashid_object = True` then I get the following error in Django admin attempting to save a model:

```
TypeError
'<' not supported between instances of 'str' and 'int'
```

<img width="714" alt="image" src="https://user-images.githubusercontent.com/2185159/153659605-ffc173f4-0cc9-4f0a-884b-538b4dfd8356.png">

**Comment by nshafer** [comment]
It looks like you have a MinValueValidator on that field, which doesn't work with a string, so either enable the hashid_object or remove the validator.

**Comment by ckcollab** [comment]
That's the confusing thing and why I shared the field definition: I didn't set this validator or anything?! Changing `enable_hashid_object` removes the error

**Comment by nshafer** [comment]
What version of Django? I just tested with 3.2 and had no problems

**Comment by ckcollab** [comment]
`Django==3.2.10` and I just tried on the latest `Django==3.2.12` as well, same problemo. Using `django-hashid-field==3.3.3`

I went to a completely different model, added this, and tried to save it in Django admin:
```python
special_id = HashidField(enable_hashid_object=False, null=True, blank=True, default=1)
```

..same error! It could definitely be something silly i am doing..

I'm down to hop in a quick Google Meet or something, I can share my environment and maybe be more helpful?

**Comment by nshafer** [comment]
My guess is you have somewhere in your code-base, or some library that is helpfully adding it. If you do something like this, what do you get?

```
In [1]: key = Book._meta.get_field("key")

In [2]: key
Out[2]: <hashid_field.field.HashidField: key>

In [3]: key.enable_hashid_object
Out[3]: False

In [4]: key.validators
Out[4]: []
```

**Comment by nshafer** [comment]
What does your model inherit from? `models.Model` that's imported `from django.db import models`?

**Comment by ckcollab** [comment]
In one case:
```py
class User(AbstractBaseUser, PermissionsMixin):
    ...
    special_id = HashidField(enable_hashid_object=False, null=True, blank=True, default=1)
```

In another case:
```py
class Booking(SoftDeletableModel):
    ...
    order_id = HashidField(enable_hashid_object=False, null=True, blank=True)

# And here's soft deletable model:
class SoftDeletableModel(models.Model):
    deleted = models.BooleanField(default=False)

    objects = SoftDeleteModelManager()
    all_objects = models.Manager()

    class Meta:
        abstract = True
```

**Comment by nshafer** [comment]
Yeah none of that is a clue of where it's coming from. I'm going to hazard a guess that something is doing a `isinstance(field, models.IntegerField)` check, which is true, but obviously doesn't work. A case where duck-typing is better in python/django. Why do you want to disable the Hashid object? Is leaving it on an option?

**Comment by nshafer** [comment]
`min_value, max_value = connection.ops.integer_field_range(internal_type)` is getting something from your adapter that I've never seen, but I'm 100% postgres in my work.

**Comment by ckcollab** [comment]
Well this is a fun one! Yeah, Postgres here, too..

```py
'ENGINE': 'django.db.backends.postgresql_psycopg2',
```

```
psycopg2-binary==2.9.3
```

**Comment by nshafer** [comment]
Version 3.3.4 is on pypi with a fix for this. Sorry about that! But thank you for working with me to a solution.

Nate

**Comment by ckcollab** [comment]
No problemo, was fun! Confirmed fixed.

Have a good one!
