### ISSUE TITLE
Extraction of original integer ID from queryset

### ISSUE THREAD

**Issue by Klim314** [nshafer/django-hashid-field#73]
There are a number of packages that implement Smart Iteration for django querysets, typically using sequential integer keys (e.g. ). These often increment the resultant key by the chunksize, and assume an integer primary key to add to.

Would there be any form of escape hatch in which we could access the internal integer value of the field?

In the case of which there is none and someone else runs into this, a workaround would be to monkeypatch in the `__add__` method, allowing down other modules to work as expected.

**Comment by nshafer** [comment]
I have added integer arithmetic methods to the Hashid object, so doing things like `book.id + 100` should work. If it doesn't, please let me know what packages you're referring to so I can attempt to duplicate the problem.
