### ISSUE TITLE
Int lookup passed as string finds object on a field with a prefix when allow_int_lookup=False

### ISSUE THREAD

**Issue by AgiNetz** [nshafer/django-hashid-field#74]
Hi, I ran into a bug where sometimes ints passed as string into a lookup would find the object. I digged in the code a bit and found the issue happens when the int string representation is shorter than the prefix on the model. In that case, this code in lookups.py:30-35

```
# Make sure int lookups are not allowed, even if prefixed, unless the
# given value is actually a hashid made up entirely of numbers.
without_prefix = value[len(field.prefix):]
if _is_int_representation(without_prefix) and without_prefix != hashid.hashid:
    raise ValueError(field.error_messages['invalid_hashid'] % {'value': value})
```

won't raise the ValueError as `without_prefix` is an empty string and `_is_int_representation` returns False for empty strings.

**Comment by nshafer** [comment]
Thank you for the report, fixed in 3.3.7 on pypi.
