### ISSUE TITLE
Please upgrade to Django 5.0

### ISSUE THREAD

**Issue by khamaileon** [nshafer/django-hashid-field#85]
Django 5.0 has been out for a week now, and it's the last package that's preventing me from upgrading.

**Comment by nshafer** [comment]
Version 3.4.0 is now on pypi with support for Django 5.0. There is one known issue that has an easy work-around: https://github.com/nshafer/django-hashid-field#known-issues

**Comment by khamaileon** [comment]
All the tests are green and everything works fine. Thank you @nshafer and happy new year!
